apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-deployment
  labels:
    app: node-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
        - name: node-web-container
          image: hansikagollen/my-new-node-image:latest
          ports:
            - containerPort: 5000
