apiVersion: v1
kind: Service
metadata:
  name: node-web-service
spec:
  type: NodePort
  selector:
    app: node-web
  ports:
    - port: 80         # Service port
      targetPort: 5000 # Container port
      nodePort: 30080  # Port exposed on the node
